spring.application.name=online-clipboard-backend

# --- Database Connection ---
# Use ${VARIABLE_NAME} to pull from environment
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- Driver Configuration ---
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate / JPA Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Increase Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Ensure server doesn't time out on slow uploads
server.tomcat.connection-timeout=20000